name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
env:
  SERVICE_CODE: "i2-bridge"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Build, tag, and push image to Docker Hub
      run: |
        docker buildx build --push \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE_CODE }}:${{ github.sha }} \
          --file Dockerfile \
          --platform linux/amd64,linux/arm64 .

    - name: Update deployment file
      run: |
        CONTENT_RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.K8_REPO_ACCESS_SECRET }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/gaiangroup/k8s-files-master/contents/helm/${{ env.SERVICE_CODE }}/values.yaml?ref=prod)
        OLD_CONTENT=$(echo "$CONTENT_RESPONSE" | jq -r .content)
        SHA=$(echo "$CONTENT_RESPONSE" | jq -r .sha)
        NEW_CONTENT=$(echo "$OLD_CONTENT" | base64 -d | sed -E "s|image:\s*gaianmobius/${{ env.SERVICE_CODE }}:[a-zA-Z0-9.]*|image: gaianmobius/${{ env.SERVICE_CODE }}:${{ github.sha }}|g; s|image:\s*\ngaianmobius/${{ env.SERVICE_CODE }}:[a-zA-Z0-9.]*|image: gaianmobius/${{ env.SERVICE_CODE }}:${{ github.sha }}|g" | base64 -w0)
        UPDATE_RESPONSE=$(curl -s -X PUT \
          -H "Authorization: Bearer ${{ secrets.K8_REPO_ACCESS_SECRET }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/gaiangroup/k8s-files-master/contents/helm/${{ env.SERVICE_CODE }}/values.yaml \
          -d "{\"message\": \"Update deployment image\", \"content\": \"$NEW_CONTENT\", \"sha\": \"$SHA\", \"branch\": \"prod\"}")

