replicaCount: 2

image:
  repository: i2-bridge
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: i2-bridge.local
      paths:
        - path: /(.*)
          pathType: Prefix

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  OTEL_COLLECTOR_URL: "http://otel-collector:4317"
  DATABASE_URL: "postgresql+asyncpg://user:pass@postgres:5432/i2bridge" 