name: Mobius Caller Workflow 
on:
  push:
    branches: [ prod ]
jobs:
  prod_job:
    if: github.ref == 'refs/heads/prod'
    uses: gaiangroup/access/.github/workflows/i2_bridge_prod.yml@dev
    with:
      SERVICE_CODE: i2-bridge
    secrets: inherit
  unauthorized_branch_job:
    if: github.ref != 'refs/heads/prod'
    runs-on: ubuntu-latest
    steps:
      - name: This is not an authorized branch, please Run on DEV or Prod or master Branch
        run: echo "This is not an authorized branch.
